name: InfinityPig
author: Kevin Velz
main: me.velz.infinitypig.InfinityPig
version: 0.3
api-version: 1.8.8
commands:
    infinitypig:
        description: InfinityPig Command
        aliases: [ipig]
        usage: /<command>